services:
  fmdd.shop_service:
    class: FMDD\SyliusShopServicePlugin\Service\ShopService
    arguments:
      - "@sylius.repository.taxon"
      - "@sylius.repository.product_taxon"
      - "@sylius.repository.product"
      - "@sylius.repository.order"
      - '@sylius.tax_rate_resolver'
      - '@sylius.tax_calculator'
      - '@sylius.product_variant_resolver.default'
      - '@sylius.context.channel'
